<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date of Birth in future</name>
   <tag></tag>
   <elementGuidId>3a250116-0c84-4ef8-94eb-f25e0908cac6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#645352c16dc31e001202f56f-feedback > div.css-1ag8dug</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='645352c16dc31e001202f56f-feedback']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d7b58b4e-c881-4c09-8a5d-b62071b7acf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1ag8dug</value>
      <webElementGuid>8a8b0652-b5a7-4545-a289-09e943a20f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Only dates today or before are allowed</value>
      <webElementGuid>3aef1feb-972c-4336-baaf-888db97f119e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;645352c16dc31e001202f56f-feedback&quot;)/div[@class=&quot;css-1ag8dug&quot;]</value>
      <webElementGuid>cdd7b117-967d-4297-af8f-62bfc63fdfc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='645352c16dc31e001202f56f-feedback']/div</value>
      <webElementGuid>32b9ecdc-eb73-4b48-a199-4c67eae1204b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected date: 6/17/2050'])[1]/following::div[2]</value>
      <webElementGuid>8ac1f661-1469-4753-9c81-af3a2e2efad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MyInfo'])[6]/following::div[4]</value>
      <webElementGuid>81f20178-430f-44f1-b995-4d66fe0c4bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MyInfo'])[7]/preceding::div[3]</value>
      <webElementGuid>d12cd5f0-3a8c-4549-8460-3b4be4880443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Only dates today or before are allowed']/parent::*</value>
      <webElementGuid>4c66be7f-d551-4421-a418-9e4e2c319027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div</value>
      <webElementGuid>85360f90-34db-4b71-a0ce-491bfe6d5e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Only dates today or before are allowed' or . = 'Only dates today or before are allowed')]</value>
      <webElementGuid>cbdd742c-5c94-4de3-9c5e-7b2de69c64e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
