<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field is required</name>
   <tag></tag>
   <elementGuidId>1cdb67f9-32bb-4382-a24a-e125bc3b2834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#6453521e35eb0c00128fa97d-feedback</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='6453521e35eb0c00128fa97d-feedback']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b794f777-42ac-49ba-b40b-465a8d037935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6453521e35eb0c00128fa97d-feedback</value>
      <webElementGuid>c745c8d6-4853-4017-8ff0-9422d3808313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>754e9877-dc7b-46f6-b9bb-1595e816dbdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-form__error-message css-1vo62p7</value>
      <webElementGuid>ee44166d-3869-4828-966e-5cf5d1ef3312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This field is required</value>
      <webElementGuid>18bc0f90-d303-44d1-a8de-efe2ae1aad98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6453521e35eb0c00128fa97d-feedback&quot;)</value>
      <webElementGuid>7af6b6d9-2ee9-4bf1-b24d-0293e5315d39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='6453521e35eb0c00128fa97d-feedback']</value>
      <webElementGuid>0a8b2405-9d5a-4caf-ba1d-a3ffab29819e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[4]/div/div/form/div/div/div[3]/div[2]</value>
      <webElementGuid>42fd3b61-6425-4bf7-9cf4-388fc4a65e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MyInfo'])[3]/following::div[1]</value>
      <webElementGuid>bb29a972-061a-40bb-975b-c0ab43962b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]</value>
      <webElementGuid>dbb7fd49-9a40-4be3-a5f3-9012385d69df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '6453521e35eb0c00128fa97d-feedback' and (text() = 'This field is required' or . = 'This field is required')]</value>
      <webElementGuid>427f44ca-d5d4-426d-bba9-4368d30cbb0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
