<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date Of Birth</name>
   <tag></tag>
   <elementGuidId>9c261a1d-be49-4bbd-89f8-154aafaae15a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='645352c16dc31e001202f56f']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#645352c16dc31e001202f56f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cac8fb7-e73f-42f9-96d1-76213a86ba9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>22e0b8ba-3d32-40af-b1a0-3a4f5e6fac96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>c647abd2-068d-4af2-be00-9af5881a66d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>bfcc33f9-bbe9-45be-acda-ab85ee7e973d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>645352c16dc31e001202f56f</value>
      <webElementGuid>eecda47b-cb5d-4bac-9179-1511b260c5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>645352c16dc31e001202f56f</value>
      <webElementGuid>de050f2b-9b21-465f-99f4-3b5efcdce821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c0837ade-3a35-4847-bf09-89c21214e9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-va9g5h focus-visible</value>
      <webElementGuid>27b51157-513b-48ce-8a70-c2fc74bc8b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>0d4ca5f1-6510-420d-bea9-db83628d5dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dc06eaf7-175a-4e44-824d-f62e338b3a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>645352c16dc31e001202f56f-feedback 645352c16dc31e001202f56f-feedback</value>
      <webElementGuid>e9244792-1803-42a6-950e-95a030980e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;645352c16dc31e001202f56f&quot;)</value>
      <webElementGuid>e8708441-b3b9-45d9-89bf-ae10e81efd67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='645352c16dc31e001202f56f']</value>
      <webElementGuid>882c24e1-7005-48fd-a48a-78cd75e3dc8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[4]/div/div/form/div/div/div[6]/div[2]/div/input</value>
      <webElementGuid>522cd718-c628-4ea4-88ba-d6b73807b735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>9c8a1dc4-1a4f-4a5c-8a54-d48f60681314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'dd/mm/yyyy' and @name = '645352c16dc31e001202f56f' and @id = '645352c16dc31e001202f56f']</value>
      <webElementGuid>404f1fff-d486-4f0f-aac0-b05aedb3f9ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
