<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email</name>
   <tag></tag>
   <elementGuidId>c6d03995-6584-4be7-b315-34cd6fe26088</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='6453521e35eb0c00128fa97d']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#6453521e35eb0c00128fa97d</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec3febc0-2f53-4a7b-b863-37149aabe662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>b23a8d38-8261-4be3-9c57-4d73a565e482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>6453521e35eb0c00128fa97d</value>
      <webElementGuid>66de80df-38a4-464d-bd22-2b5d59a05f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6453521e35eb0c00128fa97d</value>
      <webElementGuid>e3332d87-01ab-46dd-b526-d5bce3236040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>67ee71df-2d8c-455b-8df1-b53550d4d24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-1g2gyyg focus-visible</value>
      <webElementGuid>7fcbf5c9-b989-4661-b2b7-e48ba193aaa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6453521e35eb0c00128fa97d&quot;)</value>
      <webElementGuid>13b7305d-e65f-4c88-bf83-435f308446d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='6453521e35eb0c00128fa97d']</value>
      <webElementGuid>3089a9ed-2878-4442-8e18-415a8566105c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[4]/div/div/form/div/div/div[3]/input</value>
      <webElementGuid>4b233488-ecb9-4321-928c-12e5183ca22c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>3ed6cb20-9c3e-499e-8f5d-b5622e17addf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '6453521e35eb0c00128fa97d' and @id = '6453521e35eb0c00128fa97d']</value>
      <webElementGuid>72b572db-8d11-4695-8b91-d15b730fb890</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
