<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Last Name</name>
   <tag></tag>
   <elementGuidId>b1c0b84c-9eab-4aab-9fa4-b73c2bb11283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='64532b696a6af30013dc8321']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#64532b696a6af30013dc8321</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6c898c0-3824-4519-8239-a8e246102452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>2. Last Name</value>
      <webElementGuid>f517431f-08b2-4ec1-8dad-c469ddb2c827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>64532b696a6af30013dc8321</value>
      <webElementGuid>0fc9a8c8-11a4-4c27-8afe-6999864bbc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>64532b696a6af30013dc8321</value>
      <webElementGuid>c8214398-95b0-49e6-97eb-909d05cdf9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3517cd3c-fb75-4082-b5dc-9b374f45f93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-1g2gyyg focus-visible</value>
      <webElementGuid>df0a8eb7-d835-4c81-9c0a-814c4468ff56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;64532b696a6af30013dc8321&quot;)</value>
      <webElementGuid>e87e80a5-6a49-4730-b356-1b96305be8cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='64532b696a6af30013dc8321']</value>
      <webElementGuid>2080a3dc-bf0c-455f-89b4-ed8836492454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[4]/div/div/form/div/div/div[2]/input</value>
      <webElementGuid>0d1d397e-91bc-47b4-a4b5-406c88c6ce8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>51cafda8-07fa-4e87-bb04-182fc3969ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '64532b696a6af30013dc8321' and @id = '64532b696a6af30013dc8321']</value>
      <webElementGuid>2070b0df-8137-4238-a84a-1f71f856c023</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
