<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mobile Number</name>
   <tag></tag>
   <elementGuidId>43780adf-1723-4131-885e-e28a9b064016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='6453527335eb0c00128fbabf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#6453527335eb0c00128fbabf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cdf9fbb4-3ce3-49e1-864c-867faf6e2750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>8123 4567</value>
      <webElementGuid>0f2481f7-46dd-47a0-a9fd-276795a46a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>b5025b0d-7e6f-4653-b9fe-0c483ec14371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>6453527335eb0c00128fbabf</value>
      <webElementGuid>313046ba-1e8e-4499-bf77-4fbd137c75a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6453527335eb0c00128fbabf</value>
      <webElementGuid>b8757808-e570-47fe-b691-6ee1241a672d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fc4feea3-45ba-40e6-b144-ec1371023cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-r4znu1 focus-visible</value>
      <webElementGuid>0c9485b6-109c-479a-ba2f-1bce4cb7960f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6453527335eb0c00128fbabf&quot;)</value>
      <webElementGuid>4508c5ec-b199-4bd6-a6bf-e539a6bf6d57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='6453527335eb0c00128fbabf']</value>
      <webElementGuid>28ad7ec4-858e-44ca-bc2e-073a3926b588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[4]/div/div/form/div/div/div[5]/div[2]/input</value>
      <webElementGuid>7cc0ceb1-6f86-4161-b058-f34ba3f166dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>7ad0d95b-2a30-4791-b0c3-184d0814a61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '8123 4567' and @name = '6453527335eb0c00128fbabf' and @id = '6453527335eb0c00128fbabf']</value>
      <webElementGuid>4e0bebba-0ec9-488b-b0b6-55c3e8cf91ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
