<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Technical Test Form Title</name>
   <tag></tag>
   <elementGuidId>88da7351-78bb-4d73-82ee-335f9a80e10f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[3]/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.chakra-text.css-1alksd9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>bc359283-54a2-4d79-b7a1-16be0a9ff59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-1alksd9</value>
      <webElementGuid>1000157d-a57c-4a8b-8a88-4232ad380be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Technical Test Form</value>
      <webElementGuid>0496cd22-74a9-4e60-a062-42c701b5ddea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-1brywh5&quot;]/div[@class=&quot;css-1l2oahx&quot;]/div[@class=&quot;css-iosdev&quot;]/div[@class=&quot;css-909si8&quot;]/div[@class=&quot;chakra-skeleton css-cdkrf0&quot;]/h1[@class=&quot;chakra-text css-1alksd9&quot;]</value>
      <webElementGuid>549a41c8-2821-4f12-b43b-b2d13fdea2f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div/h1</value>
      <webElementGuid>908a03e6-b357-4e77-9b37-aa8d0a878589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Look for a lock ('])[1]/following::h1[1]</value>
      <webElementGuid>9318260a-911b-4202-8568-f5030cc4e507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trusted websites'])[1]/following::h1[1]</value>
      <webElementGuid>7ffe0120-1156-426e-95bb-d5db1929464b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MyInfo'])[1]/preceding::h1[1]</value>
      <webElementGuid>741f977b-7f46-4146-8c47-6082929212ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>6741550d-f63d-46a1-a595-9ebd9e143861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Technical Test Form' or . = 'Technical Test Form')]</value>
      <webElementGuid>59a88da3-4c8a-4806-981a-dcf401b3cc00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
