<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>East</name>
   <tag></tag>
   <elementGuidId>9ed588a5-b4b8-47e4-b479-80ae85561b3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='downshift-0-item-2']/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'East' or . = 'East')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#downshift-0-item-2 > div.css-j7qwjs > div.chakra-stack.css-ejdiwr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de2890cf-fb18-4d2b-8653-09a5ca5f4cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-stack css-ejdiwr</value>
      <webElementGuid>010e1f0e-afd6-479d-a761-7a083cb5503f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>East</value>
      <webElementGuid>329bf5b5-057a-4960-8c32-d9c3c5578abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downshift-0-item-2&quot;)/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;chakra-stack css-ejdiwr&quot;]</value>
      <webElementGuid>0e58801d-3b4c-47d5-81b6-f62342611602</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='downshift-0-item-2']/div/div</value>
      <webElementGuid>ba2d46b7-0ba1-4895-a049-dd09e89e546d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='South'])[1]/following::div[3]</value>
      <webElementGuid>7d755831-abb3-4f86-93dc-5cde28ae4ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='North'])[2]/following::div[6]</value>
      <webElementGuid>2e00d099-bf1e-4730-ade8-18f9dfd1ed20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='West'])[1]/preceding::div[1]</value>
      <webElementGuid>5bf9ea47-170f-4779-bf4c-0bdc8d8ffee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/li/div/div</value>
      <webElementGuid>23bfee97-f99e-4616-884c-ac2b27a380e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'East' or . = 'East')]</value>
      <webElementGuid>f7e66d2c-e547-4eac-b209-9e4ae95cdc8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
